from __future__ import annotations


COPY = {
    "app_name": "Luma",
    "tagline": "A quiet space to notice, reflect, and reframe.",
    "welcome": "A softer way to look back",
    "home_body": "Take a few unhurried minutes with a social moment that has stayed on your mind.",
    "start": "Start a reflection",
    "continue": "Continue reflection",
    "participant_id": "Participant ID",
    "participant_help": "Use the study ID you were given. Do not enter your name or contact details.",
    "consent": "I understand that approved researchers may view this conversation live, including safety flags.",
    "consent_title": "Before you begin",
    "consent_body": "You choose what to share. You can skip or end at any time.",
    "begin": "Begin gently",
    "consent_required": "Please confirm live-viewing consent before beginning.",
    "home": "Home",
    "reflect": "Reflect",
    "reflections": "Reflections",
    "support": "Support",
    "settings": "Settings",
    "back": "← Back",
    "reflection": "Reflection",
    "stage": "Step {current} of {total}",
    "skip": "Skip",
    "end_conversation": "End the conversation",
    "end_card_question": "Before we finish, would you like a reflection card based on what we have discussed?",
    "create_card_end": "Create a reflection card",
    "end_without_card": "End without a card",
    "continue_conversation": "Continue the conversation",
    "card_choice_question": "We have developed a basic reflection on what happened. Would you like a reflection card, or would you prefer to keep talking?",
    "create_reflection_card": "Create a reflection card",
    "keep_talking": "Keep talking",
    "card_generation_error": "We couldn’t create the reflection card just now. Please try again.",
    "try_again": "Try again",
    "end_title": "End this reflection?",
    "end_body": "Your responses so far will remain available to the research team. You can also return instead.",
    "end_confirm": "End reflection",
    "cancel": "Keep reflecting",
    "legacy_read_only": "This earlier reflection is read-only. You can return Home and start a new reflection.",
    "stopped": "This reflection has ended. Nothing else will be sent.",
    "completed": "Reflection complete. Thank you for taking this time.",
    "input": "Write what comes to mind…",
    "reply_error": "I could not respond just now. Your message is saved — please try again.",
    "demo": "Private preview mode · responses disappear when the app restarts",
    "draft_title": "Your reflection card",
    "draft_note": "A draft in your words — nothing appears in Saved Reflections until you choose Save.",
    "what_happened": "What happened",
    "what_meant": "What I thought it meant",
    "other": "Other possible interpretations",
    "balanced": "A more balanced reflection",
    "possible_next_steps": "A possible next step",
    "edit": "Edit",
    "regenerate": "Regenerate",
    "delete": "Delete",
    "save": "Save",
    "save_changes": "Keep changes",
    "saved": "Saved to Reflections",
    "delete_draft": "Delete this card?",
    "delete_confirm": "Delete card",
    "empty_title": "No saved reflections yet",
    "empty_body": "A reflection card will appear here only after you review and save it.",
    "support_title": "Support, when you want it",
    "support_body": "This space is for reflection. If you want more support, reaching out to someone you trust or an appropriate local service can be a next step.",
    "general_support": "General support",
    "general_support_body": "Consider a trusted friend, family member, study contact, GP, or another qualified local professional.",
    "urgent_support": "I need urgent support",
    "privacy": "Privacy",
    "privacy_body": "Your Participant ID, messages, safety flags, draft cards, and feedback may be stored for the study and viewed by approved researchers.",
    "data_controls": "Your data controls",
    "delete_data": "Delete this session’s data",
    "delete_data_warning": "This permanently removes this session, its messages, card, and feedback.",
    "confirm_delete_data": "Permanently delete",
    "exit_study": "Exit this study session",
    "exit_body": "This ends the session but does not delete data already collected.",
    "confirm_exit": "Exit session",
    "feedback_title": "A final check-in",
    "helpful": "How helpful was this reflection?",
    "understood": "I felt understood",
    "comments": "Anything else? (optional)",
    "submit_finish": "Send feedback and finish",
    "feedback_saved": "Thank you — your feedback is saved.",
    "not_started": "Start from Home when you feel ready.",
}


def text(key: str, **values: object) -> str:
    return COPY[key].format(**values)
